import { NextResponse } from 'next/server';
import { Resend } from 'resend';
import { createClient } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';

const resendApiKey = process.env.RESEND_API_KEY;
const resend = resendApiKey ? new Resend(resendApiKey) : null;

// Use Service Role Key for server-side operations to bypass RLS
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
// Check both standard name and Vercel prefix convention
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.btools_SUPABASE_SERVICE_ROLE_KEY || '';

// We MUST have the service key to bypass RLS in this route
const supabaseAdmin = (supabaseUrl && supabaseServiceKey) 
  ? createClient(supabaseUrl, supabaseServiceKey) 
  : null;

export async function POST(req: Request) {
  try {
    if (!supabaseAdmin) {
      console.error("FATAL ERROR: SUPABASE_SERVICE_ROLE_KEY (or btools_SUPABASE_SERVICE_ROLE_KEY) is missing in environment variables. Cannot bypass RLS.");
      return NextResponse.json({ error: 'Server configuration error: Missing service role key' }, { status: 500 });
    }

    const { clientId, subject, body } = await req.json();

    if (!clientId || !subject || !body) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // 1. Fetch Client Details
    const { data: client, error: clientError } = await supabaseAdmin
      .from('clients')
      .select('name, contact_email')
      .eq('id', clientId)
      .single();

    if (clientError || !client || !client.contact_email) {
      console.error("Client Fetch Error:", clientError || "Client not found or missing email");
      return NextResponse.json({ error: 'Client not found or has no contact email' }, { status: 400 });
    }

    // 2. Fetch Global Email Template
    const { data: settings, error: settingsError } = await supabaseAdmin
      .from('app_settings')
      .select('email_template')
      .eq('id', 'global')
      .single();

    let htmlTemplate = '<div>[content]</div>'; // Fallback
    if (!settingsError && settings?.email_template) {
      htmlTemplate = settings.email_template;
    }

    // 3. Prepare the HTML content
    // body is now HTML generated by ReactQuill
    const finalHtml = htmlTemplate.replace('[content]', body);

    // 4. Send Email
    let status = 'Queued';
    let resendData = null;

    if (resend) {
      const response = await resend.emails.send({
        from: 'BrandTactics <updates@brandtactics.io>',
        to: [client.contact_email],
        subject: subject,
        html: finalHtml,
      });

      if (response.error) {
        console.error("Resend Error:", response.error);
        return NextResponse.json({ error: response.error.message }, { status: 400 });
      }
      resendData = response.data;
      status = 'Delivered';
    } else {
      console.log(`[SIMULATION] Would send to ${client.contact_email}`);
      console.log(`[SIMULATION] Subject: ${subject}`);
      status = 'Delivered';
    }
    
    // 5. Log to Supabase
    const { error: logError } = await supabaseAdmin.from('email_updates').insert({
      client_id: clientId,
      title: subject,
      recipient_email: client.contact_email,
      status: status,
      sent_date: new Date().toISOString(),
      body: finalHtml
    });

    if (logError) {
      console.error("Log Error:", logError);
      // We don't return error here if email was actually sent, but it's good to know
    }

    return NextResponse.json({ success: true, simulated: !resend, data: resendData });
  } catch (error: any) {
    console.error("API Error:", error);
    return NextResponse.json({ error: error.message || 'Server error' }, { status: 500 });
  }
}
